// Boots the docker-backed dev path:
//   1. Detect docker compose vs podman compose
//   2. Bring up the local Postgres + Redis (+ srh) stack
//   3. Wait for Postgres to accept connections
//   4. Push the drizzle schema (no migrations folder hassle)
//   5. Seed ~20 approved pets so the gallery isn't empty
//   6. Hand off to next dev (turbopack, since there's no PGlite to break it)
//
// Usage:
//   bun run dev:docker
//
// .env.dev is the shared committed defaults; .env.local is layered on
// top so personal credentials win. PETDEX_MOCK is explicitly cleared
// so the mock shims don't accidentally swap real Clerk for the stub.

import { spawn, spawnSync } from "node:child_process";
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Engine = { cmd: string; args: string[] };

function detectEngine(): Engine {
  // Prefer docker, fall back to podman. Both expose the same compose v2
  // subcommand surface for our use case.
  for (const cmd of ["docker", "podman"]) {
    const r = spawnSync(cmd, ["compose", "version"], {
      stdio: "ignore",
    });
    if (r.status === 0) return { cmd, args: ["compose"] };
  }
  // Some users only have docker-compose v1 (still common on Linux).
  const v1 = spawnSync("docker-compose", ["version"], { stdio: "ignore" });
  if (v1.status === 0) return { cmd: "docker-compose", args: [] };
  console.error(
    "[dev:docker] no container engine found.\n" +
      "  Install Docker Desktop, OrbStack, or Podman, then rerun:\n" +
      "    https://docs.docker.com/get-docker/  (Docker)\n" +
      "    https://orbstack.dev                  (Mac, lightweight Docker drop-in)\n" +
      "    https://podman.io/docs/installation   (Podman)\n",
  );
  process.exit(1);
}

function loadEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    out[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  return out;
}

function compose(engine: Engine, ...rest: string[]): number {
  const r = spawnSync(engine.cmd, [...engine.args, ...rest], {
    stdio: "inherit",
  });
  return r.status ?? 1;
}

async function waitForPostgres(timeoutMs = 60_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const r = spawnSync("nc", ["-z", "127.0.0.1", "54320"], {
      stdio: "ignore",
    });
    if (r.status === 0) return;
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  throw new Error("Postgres did not become reachable on 127.0.0.1:54320");
}

async function main() {
  const root = process.cwd();
  const engine = detectEngine();
  console.log(
    `[dev:docker] using ${engine.cmd} ${engine.args.join(" ")} for compose`,
  );

  // Next loads env files in this order (dev, highest priority first):
  //   .env.development.local   <- we own this one
  //   .env.local               <- the maintainer's personal file
  //   .env.development
  //   .env
  // Anything in .env.development.local wins, which lets us override
  // the maintainer's `.env.local` (usually pointed at production)
  // without touching it. We rewrite this file on every dev:docker
  // launch and remove it on clean exit.
  const overlayPath = join(root, ".env.development.local");

  const envDev = loadEnvFile(join(root, ".env.dev"));
  const envDevLocal = loadEnvFile(join(root, ".env.dev.local"));
  const merged = { ...envDev, ...envDevLocal };
  const lines = [
    "# Auto-generated by `bun run dev:docker`. Do not edit by hand.",
    "# Source: .env.dev (committed) + .env.dev.local (personal).",
    "# Removed on clean exit; safe to delete by hand if it sticks around.",
    "",
    ...Object.entries(merged).map(([k, v]) => `${k}=${v}`),
  ];
  writeFileSync(overlayPath, `${lines.join("\n")}\n`);
  console.log("[dev:docker] wrote .env.development.local (Next overlay)");

  const cleanupOverlay = () => {
    try {
      if (existsSync(overlayPath)) unlinkSync(overlayPath);
    } catch {
      /* best effort */
    }
  };
  process.on("exit", cleanupOverlay);
  for (const sig of ["SIGINT", "SIGTERM", "SIGHUP"] as const) {
    process.on(sig, () => {
      cleanupOverlay();
      process.exit(0);
    });
  }

  const env: NodeJS.ProcessEnv = {
    ...process.env,
    ...merged,
    // Mock mode and the docker path are mutually exclusive — clear it
    // so we don't accidentally double-shim Clerk.
    PETDEX_MOCK: "",
  };

  const composeArgs = ["-f", "docker-compose.dev.yml"];

  console.log("[dev:docker] bringing up postgres + redis");
  const upStatus = compose(engine, ...composeArgs, "up", "-d");
  if (upStatus !== 0) {
    console.error("[dev:docker] compose up failed");
    process.exit(upStatus);
  }

  console.log("[dev:docker] waiting for postgres on 127.0.0.1:54320");
  try {
    await waitForPostgres();
  } catch (err) {
    console.error(`[dev:docker] ${(err as Error).message}`);
    process.exit(1);
  }

  console.log("[dev:docker] pushing schema with drizzle-kit");
  const push = spawnSync("bun", ["x", "drizzle-kit", "push", "--force"], {
    stdio: "inherit",
    env,
  });
  if (push.status !== 0) {
    console.error("[dev:docker] drizzle-kit push failed");
    process.exit(push.status ?? 1);
  }

  console.log("[dev:docker] seeding ~20 approved pets");
  const seed = spawnSync(
    "bun",
    ["--conditions", "react-server", "scripts/seed-dev.ts"],
    { stdio: "inherit", env },
  );
  if (seed.status !== 0) {
    console.error("[dev:docker] seed failed");
    process.exit(seed.status ?? 1);
  }

  console.log("[dev:docker] starting next dev (turbopack)");
  const child = spawn("bun", ["x", "next", "dev", ...process.argv.slice(2)], {
    stdio: "inherit",
    env,
  });

  // Forward signals to the child so containers stop cleanly. The exit
  // handler installed earlier restores .env.local. Containers stay up
  // by default — they're cheap and the next dev:docker boot is faster.
  for (const sig of ["SIGINT", "SIGTERM"] as const) {
    process.on(sig, () => {
      child.kill(sig);
    });
  }

  child.on("exit", (code) => {
    cleanupOverlay();
    process.exit(code ?? 0);
  });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
